language: objective-c
osx_image: xcode8.1

env:
  global:
  - APP_NAME="BLBook"
  #- 'DEVELOPER_NAME="iPhone Distribution: xiaoxin wang (57WTDCG577)"'
  - 'DEVELOPER_NAME="iPhone Distribution: xiaoxin wang"'
  - PROFILE_NAME="BLBookAdPro"
  - secure: hNtYm3WGeJumJcycXkKqZyA4EINqYbd8oj0SP1b2hZAUgOWg3nnE4oVgye3Z7T5C9AaOewfSRz6VWxNM5xhKF/rQekoOke2BWQN5eEihGX6xZf7/p5kJn6xtsYE2HgFUByLInn+uFjMi534LiZhKlRfHaTwAg/KliBQ1PiFdmfLHt0cJ0iMMfIRWWxg5djm8obZApcsA1jH/NyLZqaOTPfagmhQmLNACcLELZCr5MmpURC5QWaxIy/o+679EtEA3ZxnXf20lJi4FGzF+sGqAAKkX9vxs28sY29R/X1RFJlBWNJFWYMOfZijSwbwsSmTHH27U+cIiUBRiTqxxH5KhAcZVuVAX8e6uTCgz3FtoivI0OPo26ehMB6MFqqZY+LrxFJzzPa4UwhJsS+Dzp+xhjgQryZc5SQHYHN/jcA1WIYps6qimTnIDGAdOjezbu3SqUAIuU3Fslk+HD8mB7ABshLI0oWrbDdYTrxKP2/y6tBSml26KR/FyzetOW8IOinOk9/UGxCRmBI/CVOd56pOYw2DlL/0iexUxXN0dHf8M6l0svTy12PGnlxrrgBkcqC7sGjeI8R2YjyWTi5+ttq4Rq4OzBJ5a72EZcx2ksn8EVPeo8zZ0gP3PlWm1NHXqZNEmi43MiHwCVkBhBromAcQVJrykCIwSD6yH83QoqP8dVXE=
  - secure: hPUAFn3UqsoerRGW4QfXPxCHPDTZVo3lQBHXPI2D636lSLel28xbl/Lv0OAKZv8QJKGzfrd+VrZOUfycGpYvQV7hyOugIHqzE607w42ik7EIc7HiDsr+GkFB7yAf2TRCjjjS+BXPWBtFq6x5yQwYj7mXlInVHWRRQFrbtaN+7YCtedKcKUyasC72npSjlo3prVhW5Af163a/JgTuu5sf7gX603WPN9U7fViXuor5rZihVT1cIJonFhdn+mIoWNR0mn5shXhPOzqf5E4BDzeOVyp+dTzstTIvIIVEYoVUYEdmirfV+tnWjUcIdQYbj+qU4Brq2UnCa/rddkdn/HsbodCtN1tqAJuvBKKbrPGFmzHg9tDrJ2zorr5Wsa0/SGf6k1tlCr2HmMGnoSIOH0CQMqRyHc9yVKd6uGJ1eq1s8yV/LKBeM9XqvX90bUVnprhYsxa/PXmtMLcqQ418EeLECB38QH40YqIj5JEeo+gZPxpUe4FlFxaceORXIBv5EoVUyBSqCx3nb5k7KPQdUkZfUERRoL3U+TdEEnLj4fa0I6V6oM6NcULR86Qyu662qH2ITmqpRR/HUUOe1PoUPVf2qfFpD2NpR2jv+ppIcQlHOBev6NGiCKDtd73Vtmaml09h0k41+WoAEplfd8IDjbB8sll1KnkNi0HhjtCF1OXFzmE=
before_script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/$PROFILE_NAME.mobileprovision.enc -d -a -out scripts/profile/$PROFILE_NAME.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
script:
- xctool -workspace BLBook.xcworkspace -scheme BLBook -sdk iphoneos  -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
#- xcodebuild -workspace BLBook.xcworkspace -scheme BLBook -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="$DEVELOPER_NAME"
after_success:
- ./scripts/sign-and-upload.sh
after_script:
- ./scripts/remove-key.sh
